### ISSUE TITLE
'MetaGetBuilder' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by genepeng** [tinode/ios#151] opened 2020-05-31 02:03 UTC
not sure if it is a bug or not, when I build the app, several errors like "xxx is ambiguous for type lookup in this context" raised

![image](https://user-images.githubusercontent.com/13142694/83342750-af657200-a325-11ea-8a6c-8ec917133d26.png)

Maybe I did something wrong, please help

**Comment by or-else** [comment] 2020-05-31 06:38
I don't see it in Xcode 11.5 (11E608c):

<img width="1182" alt="Screenshot 2020-05-31 at 09 37 05" src="https://user-images.githubusercontent.com/5938143/83346127-7972be80-a322-11ea-8ea0-42f1243d5e3d.png">

**Comment by or-else** [comment] 2020-06-02 07:02
No update in 2 days. Closing.

**Closed by or-else** 2020-06-02 07:02 UTC
Labels: cannot reproduce

**Comment by 0wave** [comment] 2021-02-09 04:48
Please help! Still got the error.

Env:
macOS Mojave  10.14.5
Xcode 11.3.1
Swift 5

<img width="997" alt="屏幕快照 2021-02-09 下午12 46 45" src="https://user-images.githubusercontent.com/28330712/107317066-e86cfd80-6ad4-11eb-9605-95c11db8ee0c.png">

**Comment by or-else** [comment] 2021-02-09 05:00
Still cannot reproduce
XCode 12.4 (12D4e), Swift 5.0, macOS 11.2

<img width="896" alt="Screenshot 2021-02-08 at 20 57 40" src="https://user-images.githubusercontent.com/5938143/107317993-c3649480-6aac-11eb-8d51-53553dd3b757.png">

**Comment by 0wave** [comment] 2021-02-09 10:06
Thanks for so quick response!

Strange. This kind of errors should only related to swift. But we got the same swift version.

Couldn't upgrade macOS of this Mac. Will try in Catalina.
